---
kind: pipeline
type: docker
name: linux-amd64

platform:
  arch: amd64
  os: linux

steps:
- name: Start syncing && Compiling
  image: brock5555/recovery
  environment:
    PASSWORD:
      from_secret: gitpass
  commands:
  - bash build.sh
